InseeFr/sugoi-api

sugoi-api-services/src/main/java/fr/insee/sugoi/services/SugoiApiServicesApplication.java
=> Add configuration override

.github/workflows/docker.yml, .github/workflows/maven.yml, .gitignore, sugoi-api-core/src/main/resources/application.properties
=> add docker workflows

sugoi-api-services/pom.xml, sugoi-api-services/src/main/java/fr/insee/sugoi/services/configuration/CorsConfiguration.java, sugoi-api-services/src/main/java/fr/insee/sugoi/services/configuration/SecurityConfiguration.java, sugoi-api-services/src/main/resources/application.properties
Signed-off-by: Clement Dufaure <clementdufaure@hotmail.com>
=> add security configuration

sugoi-api-core/src/main/java/fr/insee/sugoi/core/store/impl/StoreStorageImpl.java, sugoi-api-ldap-store-provider/src/main/java/fr/insee/sugoi/store/ldap/LdapReaderStore.java, sugoi-api-ldap-store-provider/src/main/java/fr/insee/sugoi/store/ldap/LdapStoreBeans.java, sugoi-api-ldap-store-provider/src/main/java/fr/insee/sugoi/store/ldap/LdapWriterStore.java
close #25
we need prototype Scope to force bean creation
=> fix userstorage store overriding

sugoi-api-core/src/main/java/fr/insee/sugoi/core/store/WriterStore.java, sugoi-api-file-store-provider/src/main/java/fr/insee/sugoi/store/file/FileWriterStore.java, sugoi-api-jms-store-provider/src/main/java/fr/insee/sugoi/jms/JmsWriterStore.java, sugoi-api-ldap-store-provider/src/main/java/fr/insee/sugoi/store/ldap/LdapWriterStore.java
=> fix writerstore interface

sugoi-api-distribution/sugoi-api-distribution-jar/src/main/resources/application.properties, sugoi-api-rest-commons-services/src/main/java/fr/insee/sugoi/commons/services/configuration/CorsConfiguration.java, sugoi-api-rest-services/src/main/resources/application.properties
=> Add Allowed Methods to CORS configuration

sugoi-api-rest-services/pom.xml, sugoi-api-rest-services/src/main/java/fr/insee/sugoi/services/services/PermissionService.java, sugoi-api-rest-services/src/test/java/fr/insee/sugoi/services/services/PermissionServiceTests.java, sugoi-api-rest-services/src/test/resources/permissions/test-regexp-permissions.properties
=> Ensure authorization is case insensitive

.github/workflows/maven.yml
=> Avoid docker jobs for forks

sugoi-api-rest-services/src/main/java/fr/insee/sugoi/services/services/PermissionService.java, sugoi-api-rest-services/src/test/java/fr/insee/sugoi/services/services/PermissionServiceTests.java
=> Avoid NPE when userStorage is null

sugoi-api-core/src/main/java/fr/insee/sugoi/core/store/ReaderStore.java, sugoi-api-core/src/main/java/fr/insee/sugoi/core/store/WriterStore.java, sugoi-api-file-store-provider/src/main/java/fr/insee/sugoi/store/file/FileReaderStore.java, sugoi-api-file-store-provider/src/main/java/fr/insee/sugoi/store/file/FileWriterStore.java, sugoi-api-jms-store-provider/src/main/java/fr/insee/sugoi/jms/JmsWriterStore.java, sugoi-api-ldap-store-provider/src/main/java/fr/insee/sugoi/store/ldap/LdapReaderStore.java, sugoi-api-ldap-store-provider/src/main/java/fr/insee/sugoi/store/ldap/LdapWriterStore.java
There were two problems on store interfaces :
* Group methods depend on an application.
* Search methods should return a PageResult
=> fix store interfaces

sugoi-api-ldap-store-provider/pom.xml, sugoi-api-ldap-store-provider/src/main/java/fr/insee/sugoi/store/ldap/LdapReaderStore.java, sugoi-api-ldap-store-provider/src/main/java/fr/insee/sugoi/store/ldap/LdapWriterStore.java, sugoi-api-ldap-store-provider/src/test/java/fr/insee/sugoi/ldap/LdapReaderStoreTest.java, sugoi-api-ldap-store-provider/src/test/java/fr/insee/sugoi/ldap/LdapWriterStoreTest.java, sugoi-api-ldap-store-provider/src/test/resources/application.properties, sugoi-api-ldap-store-provider/src/test/resources/ldap.ldif, sugoi-api-ldap-utils/src/main/java/fr/insee/sugoi/ldap/utils/LdapUtils.java, sugoi-api-ldap-utils/src/main/java/fr/insee/sugoi/ldap/utils/mapper/ApplicationLdapMapper.java, sugoi-api-ldap-utils/src/main/java/fr/insee/sugoi/ldap/utils/mapper/GenericLdapMapper.java, sugoi-api-ldap-utils/src/main/java/fr/insee/sugoi/ldap/utils/mapper/GroupLdapMapper.java, sugoi-api-ldap-utils/src/main/java/fr/insee/sugoi/ldap/utils/mapper/ModelType.java, sugoi-api-ldap-utils/src/main/java/fr/insee/sugoi/ldap/utils/mapper/OrganizationLdapMapper.java, sugoi-api-ldap-utils/src/main/java/fr/insee/sugoi/ldap/utils/mapper/UserLdapMapper.java, sugoi-api-ldap-utils/src/main/java/fr/insee/sugoi/ldap/utils/mapper/properties/ApplicationLdap.java, sugoi-api-ldap-utils/src/main/java/fr/insee/sugoi/ldap/utils/mapper/properties/GroupLdap.java, sugoi-api-ldap-utils/src/main/java/fr/insee/sugoi/ldap/utils/mapper/properties/LdapObjectClass.java, sugoi-api-ldap-utils/src/main/java/fr/insee/sugoi/ldap/utils/mapper/properties/OrganizationLdap.java, sugoi-api-ldap-utils/src/main/java/fr/insee/sugoi/ldap/utils/mapper/properties/UserLdap.java, sugoi-api-ldap-utils/src/main/java/fr/insee/sugoi/ldap/utils/mapper/properties/utils/MapToAttribute.java
This PR depends on PR #59. The other commits should be squashed.
It implements all the methods of the reader and writer interfaces apart from credentials methods. Some questions remain on the expected behavior of the methods which may have to be fixed.
=> Implement ldap reader writer store

sugoi-api-core/src/main/java/fr/insee/sugoi/core/service/OrganizationService.java, sugoi-api-core/src/main/java/fr/insee/sugoi/core/service/impl/OrganizationServiceImpl.java, sugoi-api-rest-services/src/main/java/fr/insee/sugoi/services/controller/OrganizationController.java
Depens on #59 .
The CRUD endpoints for organization are now plugged to the store interface.
=> Plug organization controller to store

sugoi-api-ldap-store-provider/src/main/java/fr/insee/sugoi/store/ldap/LdapReaderStore.java, sugoi-api-ldap-utils/src/main/java/fr/insee/sugoi/ldap/utils/LdapFilter.java
=> fix sub filter for objectclass

sugoi-api-rest-services/src/main/java/fr/insee/sugoi/services/controller/GroupController.java, sugoi-api-rest-services/src/main/java/fr/insee/sugoi/services/controller/OrganizationController.java, sugoi-api-rest-services/src/main/java/fr/insee/sugoi/services/controller/UserController.java, sugoi-api-rest-services/src/test/java/fr/insee/sugoi/services/controller/GroupControllerTest.java, sugoi-api-rest-services/src/test/java/fr/insee/sugoi/services/controller/OrganizationControllerTest.java, sugoi-api-rest-services/src/test/java/fr/insee/sugoi/services/controller/UserControllerTest.java
=> tests and fix for controllers

sugoi-api-jms-store-provider/src/main/java/fr/insee/sugoi/jms/JmsStoreBeans.java, sugoi-api-jms-store-provider/src/main/java/fr/insee/sugoi/jms/JmsWriterStore.java, sugoi-api-jms-store-provider/src/main/java/fr/insee/sugoi/jms/listener/JmsReceiverRequest.java, sugoi-api-jms-store-provider/src/main/java/fr/insee/sugoi/jms/listener/JmsRequestRouter.java, sugoi-api-jms-store-provider/src/main/java/fr/insee/sugoi/jms/utils/Converter.java, sugoi-api-jms-store-provider/src/main/java/fr/insee/sugoi/jms/utils/JmsAtttributes.java, sugoi-api-jms-store-provider/src/main/java/fr/insee/sugoi/jms/utils/Method.java, sugoi-api-jms-utils/src/main/java/fr/insee/sugoi/jms/configuration/JmsConfiguration.java, sugoi-api-jms-utils/src/main/java/fr/insee/sugoi/jms/model/BrokerRequest.java, sugoi-api-jms-utils/src/main/java/fr/insee/sugoi/jms/writer/JmsWriter.java, sugoi-api-model/src/main/java/fr/insee/sugoi/model/Organization.java, sugoi-api-model/src/main/java/fr/insee/sugoi/model/User.java
=> 76-implements-jms-writer-and-listener

sugoi-api-ldap-store-provider/src/main/java/fr/insee/sugoi/store/ldap/LdapWriterStore.java, sugoi-api-ldap-utils/src/main/java/fr/insee/sugoi/ldap/utils/LdapFactory.java
=> Add authentication to ldap

sugoi-api-ldap-utils/src/main/java/fr/insee/sugoi/ldap/utils/mapper/GenericLdapMapper.java, sugoi-api-ldap-utils/src/main/java/fr/insee/sugoi/ldap/utils/mapper/properties/UserLdap.java, sugoi-api-ldap-utils/src/main/java/fr/insee/sugoi/ldap/utils/mapper/properties/utils/MapToMapElement.java, sugoi-api-ldap-utils/src/test/java/fr/insee/sugoi/ldap/utils/mapper/UserLdapMapperFromObjectTest.java
=> add a readonly property to ldap data model

sugoi-api-core/pom.xml, sugoi-api-core/src/main/java/fr/insee/sugoi/core/exceptions/InvalidPasswordException.java, sugoi-api-core/src/main/java/fr/insee/sugoi/core/model/PasswordChangeRequest.java, sugoi-api-core/src/main/java/fr/insee/sugoi/core/service/CredentialsService.java, sugoi-api-core/src/main/java/fr/insee/sugoi/core/service/impl/CredentialsServiceImpl.java, sugoi-api-core/src/main/java/fr/insee/sugoi/core/service/impl/PasswordServiceImpl.java, sugoi-api-core/src/main/java/fr/insee/sugoi/core/store/WriterStore.java, sugoi-api-distribution/sugoi-api-distribution-full-env/src/main/resources/ldap-data/init-ldap.ldif, sugoi-api-file-store-provider/src/main/java/fr/insee/sugoi/store/file/FileWriterStore.java, sugoi-api-jms-store-provider/src/main/java/fr/insee/sugoi/jms/JmsWriterStore.java, sugoi-api-jms-store-provider/src/main/java/fr/insee/sugoi/jms/listener/JmsRequestRouter.java, sugoi-api-jms-store-provider/src/main/java/fr/insee/sugoi/jms/utils/JmsAtttributes.java, sugoi-api-jms-store-provider/src/main/java/fr/insee/sugoi/jms/utils/Method.java, sugoi-api-ldap-store-provider/src/main/java/fr/insee/sugoi/store/ldap/LdapWriterStore.java, sugoi-api-rest-commons-services/src/main/java/fr/insee/sugoi/commons/services/configuration/SpringDocConfiguration.java, sugoi-api-rest-services/src/main/java/fr/insee/sugoi/services/controller/CredentialsController.java, sugoi-api-test/pom.xml, sugoi-api-test/src/main/resources/ldap-data/init-ldap.ldif, sugoi-api-test/src/test/java/fr/insee/sugoi/app/cucumber/glue/PasswordGlue.java, sugoi-api-test/src/test/java/fr/insee/sugoi/app/cucumber/utils/WebRequest.java, sugoi-api-test/src/test/resources/scenario/password_scenario.feature
=> Setup controller and service for credential

sugoi-api-distribution/sugoi-api-distribution-full-env/src/main/resources/application.properties
=> fix full env distribution on mac

sugoi-api-ldap-utils/src/main/java/fr/insee/sugoi/ldap/utils/mapper/GenericLdapMapper.java, sugoi-api-ldap-utils/src/test/java/fr/insee/sugoi/ldap/utils/mapper/UserLdapMapperFromAttributesTest.java, sugoi-api-model/src/main/java/fr/insee/sugoi/model/Habilitation.java
=> Fix Habilitation in ldap store

pom.xml, sugoi-api-converter/pom.xml, sugoi-api-core/pom.xml, sugoi-api-distribution/pom.xml, sugoi-api-distribution/sugoi-api-distribution-full-env/pom.xml, sugoi-api-distribution/sugoi-api-distribution-jar/pom.xml, sugoi-api-distribution/sugoi-api-distribution-war/pom.xml, sugoi-api-file-config-provider/pom.xml, sugoi-api-file-store-provider/pom.xml, sugoi-api-jms-store-provider/pom.xml, sugoi-api-jms-utils/pom.xml, sugoi-api-ldap-config-provider/pom.xml, sugoi-api-ldap-store-provider/pom.xml, sugoi-api-ldap-utils/pom.xml, sugoi-api-model/pom.xml, sugoi-api-rest-commons-services/pom.xml, sugoi-api-rest-old-services/pom.xml, sugoi-api-rest-services/pom.xml, sugoi-api-test/pom.xml
doit résoudre l'issue sur les dependances
=> Refactor dependency management

pom.xml, sugoi-api-core/src/main/java/fr/insee/sugoi/core/event/model/SugoiEvent.java, sugoi-api-core/src/main/java/fr/insee/sugoi/core/event/model/SugoiEventTypeEnum.java, sugoi-api-core/src/main/java/fr/insee/sugoi/core/event/publisher/SugoiEventPublisher.java, sugoi-api-core/src/main/java/fr/insee/sugoi/core/service/impl/ApplicationServiceImpl.java, sugoi-api-core/src/main/java/fr/insee/sugoi/core/service/impl/ConfigServiceImpl.java, sugoi-api-core/src/main/java/fr/insee/sugoi/core/service/impl/CredentialsServiceImpl.java, sugoi-api-core/src/main/java/fr/insee/sugoi/core/service/impl/GroupServiceImpl.java, sugoi-api-core/src/main/java/fr/insee/sugoi/core/service/impl/OrganizationServiceImpl.java, sugoi-api-core/src/main/java/fr/insee/sugoi/core/service/impl/UserServiceImpl.java, sugoi-api-distribution/sugoi-api-distribution-jar/pom.xml, sugoi-api-distribution/sugoi-api-distribution-war/pom.xml, sugoi-api-event-listener/pom.xml, sugoi-api-event-listener/src/main/java/fr/insee/sugoi/event/listener/SugoiEventLogProducer.java, sugoi-api-event-listener/src/main/resources/application.properties
=> implement sugoi event log publisher

sugoi-api-ldap-store-provider/src/main/java/fr/insee/sugoi/store/ldap/LdapReaderStore.java
=> Fix possible NPE on ldap store

sugoi-api-core/src/main/java/fr/insee/sugoi/core/model/SearchType.java, sugoi-api-core/src/main/java/fr/insee/sugoi/core/service/OrganizationService.java, sugoi-api-core/src/main/java/fr/insee/sugoi/core/service/UserService.java, sugoi-api-core/src/main/java/fr/insee/sugoi/core/service/impl/ApplicationServiceImpl.java, sugoi-api-core/src/main/java/fr/insee/sugoi/core/service/impl/GroupServiceImpl.java, sugoi-api-core/src/main/java/fr/insee/sugoi/core/service/impl/OrganizationServiceImpl.java, sugoi-api-core/src/main/java/fr/insee/sugoi/core/service/impl/UserServiceImpl.java, sugoi-api-ldap-store-provider/src/main/java/fr/insee/sugoi/store/ldap/LdapReaderStore.java, sugoi-api-ldap-store-provider/src/test/java/fr/insee/sugoi/ldap/LdapReaderStoreTest.java, sugoi-api-rest-services/src/main/java/fr/insee/sugoi/services/controller/OrganizationController.java, sugoi-api-rest-services/src/main/java/fr/insee/sugoi/services/controller/UserController.java, sugoi-api-rest-services/src/test/java/fr/insee/sugoi/services/controller/OrganizationControllerTest.java, sugoi-api-rest-services/src/test/java/fr/insee/sugoi/services/controller/UserControllerTest.java
=> add support for OR request

sugoi-api-event-log/src/main/java/fr/insee/sugoi/event/listener/log/SugoiEventLogProducer.java, sugoi-api-rest-services/src/main/java/fr/insee/sugoi/services/controller/ApplicationController.java, sugoi-api-rest-services/src/main/java/fr/insee/sugoi/services/controller/CredentialsController.java, sugoi-api-rest-services/src/main/java/fr/insee/sugoi/services/controller/GroupController.java, sugoi-api-rest-services/src/main/java/fr/insee/sugoi/services/controller/HabilitationController.java, sugoi-api-rest-services/src/main/java/fr/insee/sugoi/services/controller/OrganizationController.java, sugoi-api-rest-services/src/main/java/fr/insee/sugoi/services/controller/RealmController.java, sugoi-api-rest-services/src/main/java/fr/insee/sugoi/services/controller/UserController.java, sugoi-api-rest-services/src/main/java/fr/insee/sugoi/services/decider/AuthorizeMethodDecider.java, sugoi-api-rest-services/src/main/java/fr/insee/sugoi/services/services/PermissionService.java, sugoi-api-rest-services/src/main/resources/application.properties, sugoi-api-rest-services/src/test/java/fr/insee/sugoi/services/services/PermissionServiceTests.java
=> add role password manager && role application manager

sugoi-api-event-webhook/pom.xml, sugoi-api-event-webhook/src/main/java/fr/insee/sugoi/event/listener/webhook/service/impl/WebHookServiceImpl.java
=> access-resource-outside-war

sugoi-api-core/src/main/java/fr/insee/sugoi/core/service/impl/CredentialsServiceImpl.java, sugoi-api-ldap-store-provider/src/main/java/fr/insee/sugoi/store/ldap/LdapWriterStore.java
=> boolean in ldap must be in uppercase

sugoi-api-jms-store-provider/src/main/java/fr/insee/sugoi/jms/listener/JmsRequestRouter.java
=> Fix ClassCastException on jms

sugoi-api-jms-store-provider/src/main/java/fr/insee/sugoi/jms/listener/JmsRequestRouter.java, sugoi-api-jms-store-provider/src/main/java/fr/insee/sugoi/jms/utils/Converter.java
=> Use converter instead of cast

sugoi-api-jms-store-provider/src/main/java/fr/insee/sugoi/jms/utils/Converter.java
=> Trivial Fix to jms converter (temp)

sugoi-api-rest-services/src/main/java/fr/insee/sugoi/services/controller/GroupController.java
=> fix bug where isApplicationManager is used unstead of isAppManager

sugoi-api-rest-services/src/main/java/fr/insee/sugoi/services/controller/ApplicationController.java, sugoi-api-rest-services/src/main/java/fr/insee/sugoi/services/controller/GroupController.java, sugoi-api-rest-services/src/main/java/fr/insee/sugoi/services/controller/OrganizationController.java, sugoi-api-rest-services/src/main/java/fr/insee/sugoi/services/controller/UserController.java, sugoi-api-rest-services/src/test/java/fr/insee/sugoi/services/controller/ApplicationControllerTest.java, sugoi-api-rest-services/src/test/java/fr/insee/sugoi/services/controller/GroupControllerTest.java, sugoi-api-rest-services/src/test/java/fr/insee/sugoi/services/controller/OrganizationControllerTest.java, sugoi-api-rest-services/src/test/java/fr/insee/sugoi/services/controller/UserControllerTest.java
=> Fix location headers in update requests

sugoi-api-rest-services/src/main/java/fr/insee/sugoi/services/controller/GroupController.java
=> change equals to equals ignore case when updating group

sugoi-api-ldap-store-provider/src/main/java/fr/insee/sugoi/store/ldap/LdapWriterStore.java, sugoi-api-ldap-store-provider/src/test/java/fr/insee/sugoi/ldap/LdapWriterStoreTest.java
=> Create address only if necessary

sugoi-api-converter/src/main/java/fr/insee/sugoi/converter/ouganext/Groupe.java, sugoi-api-rest-old-services/src/main/java/fr/insee/sugoi/old/services/controller/ContactGroupeDomaineController.java, sugoi-api-rest-old-services/src/main/java/fr/insee/sugoi/old/services/controller/GroupeController.java
=> Implement ouganext groupe controller

sugoi-api-rest-old-services/src/main/java/fr/insee/sugoi/old/services/controller/CredentialsDomaineController.java
=> Implement ouganext credential validation enpoint

sugoi-api-rest-services/src/main/java/fr/insee/sugoi/services/controller/RealmController.java
=> repair get realms

sugoi-api-ldap-store-provider/src/main/java/fr/insee/sugoi/store/ldap/LdapReaderStore.java
=> repair build or search on ldap

sugoi-api-core/src/main/java/fr/insee/sugoi/core/realm/RealmProvider.java, sugoi-api-file-config-provider/src/main/java/fr/insee/sugoi/config/file/LocalFileRealmProviderDAO.java, sugoi-api-file-config-provider/src/test/java/fr/insee/sugoi/config/file/LocalFileWriteRealmTest.java, sugoi-api-file-config-provider/src/test/resources/realms-write.json, sugoi-api-ldap-config-provider/src/main/java/fr/insee/sugoi/config/LdapRealmProviderDAOImpl.java, sugoi-api-ldap-config-provider/src/test/java/fr/insee/sugoi/config/LdapRealmProviderWriteTest.java, sugoi-api-ldap-config-provider/src/test/resources/application-write.properties, sugoi-api-ldap-config-provider/src/test/resources/ldap-write.ldif, sugoi-api-ldap-utils/src/main/java/fr/insee/sugoi/ldap/utils/LdapUtils.java, sugoi-api-ldap-utils/src/main/java/fr/insee/sugoi/ldap/utils/mapper/GenericLdapMapper.java, sugoi-api-ldap-utils/src/main/java/fr/insee/sugoi/ldap/utils/mapper/RealmLdapMapper.java, sugoi-api-ldap-utils/src/main/java/fr/insee/sugoi/ldap/utils/mapper/UserStorageLdapMapper.java
=> Implement config write methods

sugoi-api-ldap-utils/src/main/java/fr/insee/sugoi/ldap/utils/LdapUtils.java
=> Filter objectclass when update

sugoi-api-core/src/main/java/fr/insee/sugoi/core/model/PasswordPolicyConstants.java, sugoi-api-core/src/main/java/fr/insee/sugoi/core/service/PasswordService.java, sugoi-api-core/src/main/java/fr/insee/sugoi/core/service/impl/CredentialsServiceImpl.java, sugoi-api-core/src/main/java/fr/insee/sugoi/core/service/impl/PasswordServiceImpl.java, sugoi-api-core/src/main/resources/application.properties, sugoi-api-core/src/test/java/fr/insee/sugoi/core/service/PasswordServiceTest.java, sugoi-api-distribution/sugoi-api-distribution-war/src/main/resources/application.properties, sugoi-api-model/src/main/java/fr/insee/sugoi/model/Realm.java, sugoi-api-rest-old-services/src/main/java/fr/insee/sugoi/old/services/controller/PasswordController.java, sugoi-api-test/src/test/resources/scenario/password_scenario.feature
=> 135-Generated-password-should-contain-more-than-letter

sugoi-api-converter/src/test/resources/webservice-contact-datamodel.xsd
=> Add schema link for adresses.xsd to avoid warnings with validation

sugoi-api-event-log/src/main/java/fr/insee/sugoi/event/listener/log/SugoiEventLogProducer.java, sugoi-api-event-webhook/src/main/java/fr/insee/sugoi/event/listener/webhook/SugoiEventWebHookProducer.java, sugoi-api-jms-store-provider/src/main/java/fr/insee/sugoi/jms/JmsWriterStore.java, sugoi-api-jms-store-provider/src/main/java/fr/insee/sugoi/jms/listener/JmsRequestRouter.java, sugoi-api-jms-store-provider/src/main/java/fr/insee/sugoi/jms/utils/Converter.java, sugoi-api-jms-utils/src/test/java/fr/insee/sugoi/jms/JmsBrokerTests.java, sugoi-api-test/src/test/java/fr/insee/sugoi/app/cucumber/glue/OrganizationGlue.java, sugoi-api-test/src/test/java/fr/insee/sugoi/app/cucumber/glue/PasswordGlue.java, sugoi-api-test/src/test/java/fr/insee/sugoi/app/cucumber/glue/RealmGlue.java, sugoi-api-test/src/test/java/fr/insee/sugoi/app/cucumber/glue/UserGlue.java
=> Fix some ide warnings

sugoi-api-distribution/sugoi-api-distribution-jar/pom.xml, sugoi-api-distribution/sugoi-api-distribution-war/pom.xml, sugoi-api-event-log/pom.xml, sugoi-api-event-webhook/pom.xml, sugoi-api-file-config-provider/pom.xml, sugoi-api-rest-services/pom.xml
=> Fix some pom related warnings

sugoi-api-distribution/sugoi-api-distribution-full-env/src/main/java/fr/insee/sugoi/app/service/TomcatEmbeddedService.java, sugoi-api-jms-utils/src/main/java/fr/insee/sugoi/jms/model/BrokerRequest.java, sugoi-api-jms-utils/src/main/java/fr/insee/sugoi/jms/model/BrokerResponse.java, sugoi-api-ldap-store-provider/src/test/java/fr/insee/sugoi/ldap/LdapReaderStoreTest.java, sugoi-api-rest-old-services/src/main/java/fr/insee/sugoi/old/services/controller/ContactPasswordDomaineController.java
=> Remove useless todos

sugoi-api-distribution/sugoi-api-distribution-jar/pom.xml
=> Fix jar distribution

.github/workflows/tag.yml
=> CI - PR on tag

sugoi-api-core/src/main/java/fr/insee/sugoi/core/service/impl/GroupServiceImpl.java
A quick fix, i think it's easier to pass the config of the user in the getWriterStore than in the addUserToGroup
=> fix choose right userSource when adding or removing user from group

sugoi-api-ldap-utils/src/main/java/fr/insee/sugoi/ldap/utils/mapper/GenericLdapMapper.java, sugoi-api-ldap-utils/src/main/java/fr/insee/sugoi/ldap/utils/mapper/properties/UserLdap.java, sugoi-api-ldap-utils/src/main/java/fr/insee/sugoi/ldap/utils/mapper/properties/utils/MapToAttribute.java, sugoi-api-ldap-utils/src/test/java/fr/insee/sugoi/ldap/utils/mapper/ApplicationLdapMapperFromObjectTest.java
Groups on user are readonly.
Fixes #221
=> Fix updating users with groups

sugoi-api-rest-services/src/main/java/fr/insee/sugoi/services/controller/GroupController.java, sugoi-api-rest-services/src/test/java/fr/insee/sugoi/services/controller/GroupControllerTest.java
=> Application as pathvariable in group controller

sugoi-api-rest-old-services/src/main/java/fr/insee/sugoi/old/services/controller/IdController.java
=> Implement ouganext id controller

sugoi-api-core/src/main/java/fr/insee/sugoi/core/configuration/GlobalKeysConfig.java, sugoi-api-core/src/main/java/fr/insee/sugoi/core/event/configuration/EventKeysConfig.java, sugoi-api-core/src/main/java/fr/insee/sugoi/core/service/impl/ApplicationServiceImpl.java, sugoi-api-core/src/main/java/fr/insee/sugoi/core/service/impl/ConfigServiceImpl.java, sugoi-api-core/src/main/java/fr/insee/sugoi/core/service/impl/CredentialsServiceImpl.java, sugoi-api-core/src/main/java/fr/insee/sugoi/core/service/impl/GroupServiceImpl.java, sugoi-api-core/src/main/java/fr/insee/sugoi/core/service/impl/OrganizationServiceImpl.java, sugoi-api-core/src/main/java/fr/insee/sugoi/core/service/impl/UserServiceImpl.java, sugoi-api-event-log/src/main/java/fr/insee/sugoi/event/listener/log/SugoiEventLogProducer.java, sugoi-api-event-webhook/src/main/java/fr/insee/sugoi/event/listener/webhook/SugoiEventWebHookProducer.java, sugoi-api-event-webhook/src/main/java/fr/insee/sugoi/event/listener/webhook/service/impl/WebHookServiceImpl.java, sugoi-api-file-store-provider/src/main/java/fr/insee/sugoi/store/file/FileReaderStore.java, sugoi-api-file-store-provider/src/main/java/fr/insee/sugoi/store/file/FileStoreBeans.java, sugoi-api-file-store-provider/src/main/java/fr/insee/sugoi/store/file/FileWriterStore.java, sugoi-api-file-store-provider/src/main/java/fr/insee/sugoi/store/file/configuration/FileKeysConfig.java, sugoi-api-jms-utils/src/main/java/fr/insee/sugoi/jms/configuration/JmsKeysConfig.java, sugoi-api-ldap-store-provider/src/main/java/fr/insee/sugoi/store/ldap/LdapReaderStore.java, sugoi-api-ldap-store-provider/src/main/java/fr/insee/sugoi/store/ldap/LdapStore.java, sugoi-api-ldap-store-provider/src/main/java/fr/insee/sugoi/store/ldap/LdapStoreBeans.java, sugoi-api-ldap-store-provider/src/main/java/fr/insee/sugoi/store/ldap/LdapWriterStore.java, sugoi-api-ldap-utils/src/main/java/fr/insee/sugoi/ldap/utils/LdapFactory.java, sugoi-api-ldap-utils/src/main/java/fr/insee/sugoi/ldap/utils/config/LdapConfigKeys.java, sugoi-api-ldap-utils/src/main/java/fr/insee/sugoi/ldap/utils/mapper/GenericLdapMapper.java, sugoi-api-rest-services/src/main/java/fr/insee/sugoi/services/controller/CredentialsController.java, sugoi-api-rest-services/src/main/java/fr/insee/sugoi/services/controller/OrganizationController.java, sugoi-api-rest-services/src/main/java/fr/insee/sugoi/services/controller/UserController.java
=> Resolve 215 - Add constant for realm config keys

sugoi-api-ldap-store-provider/src/test/java/fr/insee/sugoi/ldap/LdapReaderStoreTest.java, sugoi-api-ldap-store-provider/src/test/java/fr/insee/sugoi/ldap/LdapWriterStoreTest.java, sugoi-api-ldap-store-provider/src/test/resources/ldap.ldif, sugoi-api-ldap-utils/src/main/java/fr/insee/sugoi/ldap/utils/mapper/properties/UserLdap.java
=> Add an attribute otherMails to User

sugoi-api-rest-commons-services/src/main/java/fr/insee/sugoi/commons/services/configuration/RequestRejectConfiguration.java
=> fix 264 - Send a 400 error instead of 500 when request is rejected

sugoi-api-rest-services/src/main/java/fr/insee/sugoi/services/controller/GroupController.java, sugoi-api-test/src/test/resources/scenario/group_scenario2.feature
=> fix 265 - permission on /groups use bad argument

sugoi-api-event-metrics/src/main/java/fr/insee/sugoi/event/listener/metrics/SugoiEventMetrics.java, sugoi-api-test/src/test/resources/scenario/realms_scenario.feature
Signed-off-by: Donatien Eneman <donatien.enaman@insee.fr>
=> fix: [272]  resolve 500 error when get realm not exist

sugoi-api-ldap-store-provider/src/main/java/fr/insee/sugoi/store/ldap/LdapWriterStore.java
=> Resolve [280] Create application doesn't create all object in ldap

sugoi-api-rest-services/src/main/java/fr/insee/sugoi/services/controller/UserController.java, sugoi-api-test/src/test/java/fr/insee/sugoi/app/cucumber/glue/UserGlue.java, sugoi-api-test/src/test/resources/scenario/user_tomcat1_scenario.feature
=> Resolve [288] add search users by email

sugoi-api-ldap-store-provider/src/main/java/fr/insee/sugoi/store/ldap/LdapReaderStore.java, sugoi-api-ldap-store-provider/src/main/java/fr/insee/sugoi/store/ldap/LdapWriterStore.java
Fix [291] Cannot get app if the ou=groupsourcepattern doesn't exist in ldap + create entry ou=groupsourcepattern if not already exist when create group
close #291 
=> Fix [291] Cannot get app if the ou=groupsourcepattern doesn't exist

sugoi-api-rest-services/src/main/java/fr/insee/sugoi/services/decider/AuthorizeMethodDecider.java
=> Fix [295] :bug: A writer should be a reader

sugoi-api-core/src/main/java/fr/insee/sugoi/core/service/impl/OrganizationServiceImpl.java, sugoi-api-core/src/main/java/fr/insee/sugoi/core/service/impl/UserServiceImpl.java
=> Fix [298] Error when search for users on multiple userStorage

sugoi-api-rest-services/src/main/java/fr/insee/sugoi/services/controller/OrganizationController.java
=> Resolve [301] add search mail params on organizations

sugoi-api-core/src/main/java/fr/insee/sugoi/core/service/impl/OrganizationServiceImpl.java, sugoi-api-core/src/main/java/fr/insee/sugoi/core/service/impl/UserServiceImpl.java, sugoi-api-core/src/test/java/fr/insee/sugoi/core/service/OrganizationServiceTest.java, sugoi-api-core/src/test/java/fr/insee/sugoi/core/service/UserServiceTest.java
=> fix Bug when findById in all the realm

sugoi-api-core/src/main/java/fr/insee/sugoi/core/exceptions/InvalidPasswordException.java, sugoi-api-core/src/main/java/fr/insee/sugoi/core/exceptions/PasswordPolicyNotMetException.java, sugoi-api-rest-commons-services/src/main/java/fr/insee/sugoi/commons/services/controller/technics/SugoiAdviceController.java, sugoi-api-test/src/test/resources/scenario/password_scenario.feature
=> Fix [310] :bug: Some exceptions are not caugth by SugoiAdviceController

docs/realm-configuration.md
=> Resolve [279] :books: Document realm configuration

sugoi-api-file-store-provider/src/main/java/fr/insee/sugoi/store/file/FileReaderStore.java, sugoi-api-file-store-provider/src/test/java/fr/insee/sugoi/store/file/FileReaderStoreTest.java, sugoi-api-ldap-store-provider/src/main/java/fr/insee/sugoi/store/ldap/LdapReaderStore.java, sugoi-api-ldap-store-provider/src/test/java/fr/insee/sugoi/ldap/LdapReaderStoreTest.java
=> Fix [320] :bug: NPE when getting users from a non existant group

sugoi-api-rest-commons-services/src/main/java/fr/insee/sugoi/commons/services/configuration/SecurityConfiguration.java, sugoi-api-rest-commons-services/src/main/resources/application.properties, sugoi-api-rest-services/src/main/java/fr/insee/sugoi/services/controller/WhoAmi.java, sugoi-api-rest-services/src/main/java/fr/insee/sugoi/services/services/PermissionService.java, sugoi-api-rest-services/src/main/java/fr/insee/sugoi/services/view/WhoamiView.java, sugoi-api-test/src/test/java/fr/insee/sugoi/app/cucumber/glue/WhoamiGlue.java, sugoi-api-test/src/test/java/fr/insee/sugoi/app/cucumber/utils/WhoamiView.java, sugoi-api-test/src/test/resources/scenario/whoami.feature
=> fix 263 - add whoami endpoint

sugoi-api-ldap-store-provider/src/test/java/fr/insee/sugoi/ldap/LdapReaderStoreTest.java, sugoi-api-ldap-store-provider/src/test/java/fr/insee/sugoi/ldap/LdapWriterStoreTest.java, sugoi-api-ldap-store-provider/src/test/resources/ldap.ldif
=> ✅ Add tests to password store method

docs/concepts.md, docs/realm-configuration.md, pom.xml, sugoi-api-core/src/main/java/fr/insee/sugoi/core/configuration/GlobalKeysConfig.java, sugoi-api-core/src/main/java/fr/insee/sugoi/core/seealso/MapProtocolSeeAlsoDecorator.java, sugoi-api-core/src/main/java/fr/insee/sugoi/core/seealso/SeeAlsoDecorator.java, sugoi-api-core/src/main/java/fr/insee/sugoi/core/seealso/SeeAlsoService.java, sugoi-api-core/src/main/java/fr/insee/sugoi/core/service/impl/UserServiceImpl.java, sugoi-api-core/src/test/java/fr/insee/sugoi/core/service/SeeAlsoServiceTest.java, sugoi-api-distribution/sugoi-api-distribution-full-env/src/main/resources/ldap-data/init-ldap.ldif, sugoi-api-distribution/sugoi-api-distribution-jar/pom.xml, sugoi-api-distribution/sugoi-api-distribution-war/pom.xml, sugoi-api-ldap-utils/src/main/java/fr/insee/sugoi/ldap/utils/mapper/GenericLdapMapper.java, sugoi-api-ldap-utils/src/main/java/fr/insee/sugoi/ldap/utils/mapper/RealmLdapMapper.java, sugoi-api-ldap-utils/src/main/java/fr/insee/sugoi/ldap/utils/mapper/properties/UserLdap.java, sugoi-api-model/src/main/java/fr/insee/sugoi/model/User.java, sugoi-api-seealso-http/pom.xml, sugoi-api-seealso-http/src/main/java/fr/insee/sugoi/seealso/HttpSeeAlsoDecorator.java, sugoi-api-seealso-http/src/test/java/fr/insee/sugoi/seealso/HttpSeeAlsoDecoratorTest.java, sugoi-api-seealso-ldap/pom.xml, sugoi-api-seealso-ldap/src/main/java/fr/insee/sugoi/seealso/LdapSeeAlsoDecorator.java, sugoi-api-seealso-ldap/src/test/java/fr/insee/sugoi/seealso/LdapSeeAlsoDecoratorTest.java, sugoi-api-seealso-ldap/src/test/resources/application.properties, sugoi-api-seealso-ldap/src/test/resources/ldap.ldif
=> Add SeeAlso to User

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/discussion.md, .github/ISSUE_TEMPLATE/docs.md, .github/ISSUE_TEMPLATE/feature_request.md
=> [META] 📇 Add github issue template

.github/dependabot.yml
=> [META] 📇 Fix dependabot configuration

sugoi-api-core/src/main/java/fr/insee/sugoi/core/store/ReaderStore.java, sugoi-api-core/src/main/java/fr/insee/sugoi/core/store/WriterStore.java
=> [DOC] 📚 Document ReaderStore and WriterStore (#313)

.github/workflows/check-commits.yml
Commit message should be in the form `[TYPE] message (#issuenumber)`
=> [META] 📇 Add commit message check on PR

sugoi-api-ldap-utils/src/main/java/fr/insee/sugoi/ldap/utils/LdapFactory.java
=> [FIX] 🐛: Update ldap pool connection when config change

sugoi-api-rest-services/src/main/java/fr/insee/sugoi/services/controller/AppManagedUserAttributeController.java
=> [BUG] :bug: unable to delete app managed when user not writer (#360)

docs/configuration.md, sugoi-api-rest-commons-services/src/main/java/fr/insee/sugoi/commons/services/configuration/SecurityConfiguration.java, sugoi-api-test/src/main/resources/tomcat-properties/tomcat1.properties, sugoi-api-test/src/test/resources/scenario/monitoring_scenario.feature
=> [FEAT] ✨Allow to define a local monitoring user (#367)

.github/workflows/tag.yml
=> [BUG] 🐛Fix release action

sugoi-api-ldap-config-provider/src/main/java/fr/insee/sugoi/config/LdapRealmProviderDAOImpl.java
=> [BUG] 🐛 Fix ldap connexion leak (#379)

.github/workflows/tag.yml
=> [META] :card_index: change commit message when releasing

.github/workflows/tag.yml
=> [BUG] :bug: Signoff commit when preparing release

CHANGELOG.md, sugoi-api-ldap-store-provider/src/main/java/fr/insee/sugoi/store/ldap/LdapReaderStore.java, sugoi-api-ldap-utils/src/main/java/fr/insee/sugoi/ldap/utils/LdapFactory.java
=> [BUG] 🐛  Renew connection with ldap if server is down

.github/workflows/tag.yml, CHANGELOG.md, pom.xml, sugoi-api-core/src/main/java/fr/insee/sugoi/core/service/impl/PermissionServiceImpl.java, sugoi-api-test/src/test/java/fr/insee/sugoi/app/cucumber/glue/WhoamiGlue.java
=> [BUG] 🐛 fix some sonar/compilation warnings

sugoi-api-core/src/main/java/fr/insee/sugoi/core/configuration/GlobalKeysConfig.java, sugoi-api-distribution/sugoi-api-distribution-full-env/src/main/resources/ldap-data/init-ldap.ldif, sugoi-api-distribution/sugoi-api-distribution-full-env/src/main/resources/tomcat-properties/tomcat2.properties, sugoi-api-ldap-utils/src/main/java/fr/insee/sugoi/ldap/utils/mapper/RealmLdapMapper.java
=> [ENH] :sparkles: allow to add realm description on ui-side

sugoi-api-core/src/main/java/fr/insee/sugoi/core/service/impl/GroupServiceImpl.java
=> [FIX] Delete member group dont work when multi storage (#412)

sugoi-api-rest-commons-services/src/main/java/fr/insee/sugoi/commons/services/configuration/SecurityConfiguration.java, sugoi-api-rest-commons-services/src/main/resources/application.properties
=> [ENH] role claim more generic

sugoi-api-core/src/main/java/fr/insee/sugoi/core/configuration/UiMappingService.java, sugoi-api-core/src/main/java/fr/insee/sugoi/core/model/UiField.java, sugoi-api-distribution/sugoi-api-distribution-full-env/src/main/resources/ldap-data/init-ldap.ldif, sugoi-api-distribution/sugoi-api-distribution-full-env/src/main/resources/tomcat-properties/tomcat1.properties, sugoi-api-distribution/sugoi-api-distribution-jar/src/main/resources/application.properties, sugoi-api-ldap-config-provider/src/main/java/fr/insee/sugoi/config/LdapRealmProviderDAOImpl.java, sugoi-api-ldap-config-provider/src/test/java/fr/insee/sugoi/config/LdapRealmProviderDAOOtherSuffixTest.java, sugoi-api-ldap-config-provider/src/test/java/fr/insee/sugoi/config/LdapRealmProviderDAOTest.java, sugoi-api-ldap-config-provider/src/test/java/fr/insee/sugoi/config/LdapRealmProviderWriteTest.java, sugoi-api-ldap-utils/src/main/java/fr/insee/sugoi/ldap/utils/mapper/RealmLdapMapper.java, sugoi-api-model/src/main/java/fr/insee/sugoi/model/Realm.java
=> [ENH] ✨ add ui field configuration in realm

.gitignore, sugoi-api-core/src/main/java/fr/insee/sugoi/core/configuration/UiMappingService.java, sugoi-api-distribution/sugoi-api-distribution-jar/src/main/resources/application.properties, sugoi-api-distribution/sugoi-api-distribution-war/src/main/resources/application.properties, sugoi-api-ldap-config-provider/src/main/java/fr/insee/sugoi/config/LdapRealmProviderDAOImpl.java
=> [BUG] :bug: repair ui mapping

sugoi-api-distribution/sugoi-api-distribution-jar/src/main/resources/application.properties, sugoi-api-distribution/sugoi-api-distribution-war/src/main/resources/application.properties
=> [FIX] adjust default values

sugoi-api-core/src/main/java/fr/insee/sugoi/core/configuration/UiMappingService.java, sugoi-api-core/src/main/java/fr/insee/sugoi/core/model/UiField.java, sugoi-api-distribution/sugoi-api-distribution-jar/src/main/resources/application.properties, sugoi-api-distribution/sugoi-api-distribution-war/src/main/resources/application.properties, sugoi-api-ldap-config-provider/src/main/java/fr/insee/sugoi/config/LdapRealmProviderDAOImpl.java
=> [ENH] Sort ui items

sugoi-api-core/src/main/java/fr/insee/sugoi/core/configuration/UiMappingService.java, sugoi-api-distribution/sugoi-api-distribution-jar/src/main/resources/application.properties, sugoi-api-distribution/sugoi-api-distribution-war/src/main/resources/application.properties, sugoi-api-rest-services/src/main/java/fr/insee/sugoi/services/controller/AppManagedUserAttributeController.java
=> [FIX] adjust habilitation endpoints

sugoi-api-ldap-utils/src/main/java/fr/insee/sugoi/ldap/utils/mapper/GenericLdapMapper.java, sugoi-api-model/src/main/java/fr/insee/sugoi/model/Habilitation.java
=> [FIX] accept generic strings for searching habilitations

sugoi-api-rest-services/src/main/java/fr/insee/sugoi/services/controller/UserController.java
=> [FIX] adjust mapping of search parameters

sugoi-api-distribution/sugoi-api-distribution-jar/src/main/resources/application.properties
Signed-off-by: Chemin Cecile <cecile.chemin@insee.fr>
=> Default ui mapping passwordlastchange not modifiable

sugoi-api-core/src/main/java/fr/insee/sugoi/core/service/ConfigService.java, sugoi-api-core/src/test/java/fr/insee/sugoi/core/service/ConfigServiceTest.java, sugoi-api-event-metrics/src/main/java/fr/insee/sugoi/event/listener/metrics/SugoiEventMetrics.java
=> Fix event without realm name

sugoi-api-core/src/main/java/fr/insee/sugoi/core/model/SugoiRandomPasswordCharacterData.java, sugoi-api-core/src/main/java/fr/insee/sugoi/core/service/impl/PasswordServiceImpl.java
=> [ENH] only generate friendly password (#459)

sugoi-api-jms-store-provider/src/main/java/fr/insee/sugoi/jms/JmsWriterStore.java
=> [BUG] unable to add app managed attribute from jms writer

sugoi-api-ldap-store-provider/src/main/java/fr/insee/sugoi/store/ldap/LdapWriterStore.java
=> [BUG] bad duplicate email check

docs/configuration.md, sugoi-api-core/src/main/java/fr/insee/sugoi/core/model/SugoiRandomIdCharacterData.java, sugoi-api-core/src/main/java/fr/insee/sugoi/core/service/impl/UserServiceImpl.java, sugoi-api-distribution/sugoi-api-distribution-full-env/src/main/resources/tomcat-properties/tomcat1.properties, sugoi-api-distribution/sugoi-api-distribution-full-env/src/main/resources/tomcat-properties/tomcat2.properties, sugoi-api-distribution/sugoi-api-distribution-jar/src/main/resources/application.properties, sugoi-api-distribution/sugoi-api-distribution-war/src/main/resources/application.properties, sugoi-api-ldap-store-provider/src/main/java/fr/insee/sugoi/store/ldap/LdapWriterStore.java, sugoi-api-test/src/main/resources/tomcat-properties/tomcat2.properties, sugoi-api-test/src/test/java/fr/insee/sugoi/app/cucumber/glue/UserGlue.java, sugoi-api-test/src/test/resources/scenario/user_scenario_sync.feature
=> [ENH] generate id if missing and better id and mail unicity check

sugoi-api-event-log/src/main/java/fr/insee/sugoi/event/listener/log/SugoiEventLogProducer.java, sugoi-api-event-metrics/src/main/java/fr/insee/sugoi/event/listener/metrics/SugoiEventMetrics.java, sugoi-api-event-webhook/src/main/java/fr/insee/sugoi/event/listener/webhook/SugoiEventWebHookProducer.java
=> :bug: [BUG] Fail in event doesn't stop request-process

sugoi-api-ldap-store-provider/src/main/java/fr/insee/sugoi/store/ldap/LdapReaderStore.java
=> [BUG] :bug: Get application get 200 groups instead of 20 (#468)

README.md, docs/concepts.md, docs/configuration.md, docs/realm-configuration.md
=> [ENH] :memo: Add documentation on webhooks

sugoi-api-core/src/main/java/fr/insee/sugoi/core/event/configuration/EventKeysConfig.java, sugoi-api-core/src/main/java/fr/insee/sugoi/core/service/CredentialsService.java, sugoi-api-core/src/main/java/fr/insee/sugoi/core/service/impl/CredentialsServiceImpl.java, sugoi-api-core/src/main/java/fr/insee/sugoi/core/store/WriterStore.java, sugoi-api-file-store-provider/src/main/java/fr/insee/sugoi/store/file/FileWriterStore.java, sugoi-api-jms-store-provider/src/main/java/fr/insee/sugoi/jms/JmsWriterStore.java, sugoi-api-jms-store-provider/src/main/java/fr/insee/sugoi/jms/listener/JmsRequestRouter.java, sugoi-api-ldap-store-provider/src/main/java/fr/insee/sugoi/store/ldap/LdapWriterStore.java, sugoi-api-ldap-store-provider/src/test/java/fr/insee/sugoi/ldap/LdapWriterStoreTest.java, sugoi-api-rest-old-services/src/main/java/fr/insee/sugoi/old/services/controller/ContactPasswordDomaineController.java, sugoi-api-rest-services/src/main/java/fr/insee/sugoi/services/controller/CredentialsController.java
=> [ENH] :recycle: Pass passwords to CredentialsService instead of PCR

docs/realm-configuration.md, sugoi-api-distribution/sugoi-api-distribution-full-env/src/main/resources/ldap-data/init-ldap.ldif, sugoi-api-ldap-store-provider/src/test/java/fr/insee/sugoi/ldap/LdapReaderStoreTest.java, sugoi-api-ldap-utils/src/main/java/fr/insee/sugoi/ldap/utils/mapper/GenericLdapMapper.java, sugoi-api-ldap-utils/src/main/java/fr/insee/sugoi/ldap/utils/mapper/ModelType.java, sugoi-api-ldap-utils/src/test/java/fr/insee/sugoi/ldap/utils/mapper/UserLdapMapperFromAttributesTest.java
=> [ENH] :sparkles: Add a ldap mapping type exists (#519)

sugoi-api-core/src/main/java/fr/insee/sugoi/core/service/impl/UserServiceImpl.java, sugoi-api-ldap-store-provider/src/test/java/fr/insee/sugoi/ldap/LdapWriterStoreTest.java, sugoi-api-ldap-utils/src/main/java/fr/insee/sugoi/ldap/utils/LdapUtils.java, sugoi-api-ldap-utils/src/main/java/fr/insee/sugoi/ldap/utils/mapper/GenericLdapMapper.java, sugoi-api-ldap-utils/src/test/java/fr/insee/sugoi/ldap/utils/mapper/GroupLdapMapperFromObjectTest.java, sugoi-api-test/src/test/java/fr/insee/sugoi/app/cucumber/glue/UserGlue.java, sugoi-api-test/src/test/resources/scenario/user_scenario_sync.feature
=> [ENH] delete attribute if it has only a blank or empty value

pom.xml, sugoi-api-model/pom.xml
=> [FIX] :ambulance: fix cve log4j2, avoid injection code

docs/realm-configuration.md, sugoi-api-core/src/main/java/fr/insee/sugoi/core/configuration/UiMappingService.java, sugoi-api-ldap-config-provider/src/main/java/fr/insee/sugoi/config/LdapRealmProviderDAOImpl.java, sugoi-api-ldap-config-provider/src/test/java/fr/insee/sugoi/config/LdapRealmProviderDAOTest.java, sugoi-api-ldap-config-provider/src/test/resources/ldap2.ldif, sugoi-api-ldap-utils/src/main/java/fr/insee/sugoi/ldap/utils/mapper/RealmLdapMapper.java, sugoi-api-model/src/main/java/fr/insee/sugoi/model/Realm.java, sugoi-api-model/src/main/java/fr/insee/sugoi/model/technics/UiField.java, sugoi-api-model/src/test/java/fr/insee/sugoi/model/SerializeTest.java
=> [ENH] :rotating_light: Fix warnings on UiFields

pom.xml, sugoi-api-model/pom.xml, sugoi-api-model/src/main/java/fr/insee/sugoi/model/Realm.java, sugoi-api-model/src/main/java/fr/insee/sugoi/model/UserStorage.java
=> Add IgnoreSizeOf for realm cache sizing

sugoi-api-event-webhook/src/main/java/fr/insee/sugoi/event/listener/webhook/SugoiEventWebHookProducer.java
=> [FIX] :bug: Avoid null pointer exception on webhook event handler

sugoi-api-file-config-provider/src/main/java/fr/insee/sugoi/config/file/LocalFileRealmProviderDAO.java, sugoi-api-file-config-provider/src/test/java/fr/insee/sugoi/config/file/LocalFileWriteRealmTest.java
=> [BUG] :bug: Fix update realm on file store

docs/realm-configuration.md
=> [DOC] 📝 Fix UiField options documentation

sugoi-api-core/src/main/java/fr/insee/sugoi/core/configuration/UiMappingService.java, sugoi-api-core/src/test/java/fr/insee/sugoi/core/service/UiMappingServiceTest.java, sugoi-api-ldap-config-provider/src/test/java/fr/insee/sugoi/config/LdapRealmProviderWriteTest.java, sugoi-api-ldap-utils/src/main/java/fr/insee/sugoi/ldap/utils/mapper/RealmLdapMapper.java, sugoi-api-model/src/main/java/fr/insee/sugoi/model/technics/UiField.java, sugoi-api-test/src/test/java/fr/insee/sugoi/app/cucumber/glue/RealmGlue.java, sugoi-api-test/src/test/resources/scenario/realms_scenario_sync.feature
=> [BUG] :bug: UiField should be written on realm via API (#599)

sugoi-api-ldap-store-provider/src/test/java/fr/insee/sugoi/ldap/LdapReaderStoreTest.java, sugoi-api-ldap-store-provider/src/test/resources/ldap.ldif, sugoi-api-ldap-utils/src/main/java/fr/insee/sugoi/ldap/utils/mapper/GenericLdapMapper.java
=> [BUG] :bug: fix group filter on user in ldap

sugoi-api-ldap-store-provider/src/main/java/fr/insee/sugoi/store/ldap/LdapWriterStore.java, sugoi-api-test/src/test/java/fr/insee/sugoi/app/cucumber/configuration/RestTemplateConfiguration.java, sugoi-api-test/src/test/java/fr/insee/sugoi/app/cucumber/glue/GenericGlue.java, sugoi-api-test/src/test/java/fr/insee/sugoi/app/cucumber/utils/WebRequest.java, sugoi-api-test/src/test/resources/scenario/user_scenario_sync.feature
Signed-off-by: Donatien ENEMAN <donatien.eneman@insee.fr>
=> [BUG] :bug: fix bug when adding 2 times same app-managed-attributes

sugoi-api-distribution/sugoi-api-distribution-jar/pom.xml, sugoi-api-distribution/sugoi-api-distribution-war/pom.xml
=> [BUG] :heavy_minus_sign: Remove wagon-ftp

sugoi-api-core/src/main/java/fr/insee/sugoi/core/realm/RealmProvider.java, sugoi-api-core/src/main/java/fr/insee/sugoi/core/store/impl/StoreProviderImpl.java
=> [BUG] :bug: load US causes realm cache to be avoided

pom.xml
Signed-off-by: Mehdi Maaref <mehdi.maaref@insee.fr>
=> [UP] :arrow_up: Bump spingboot.version from 2.6.4 to 2.6.6

sugoi-api-ldap-store-provider/src/main/java/fr/insee/sugoi/store/ldap/LdapWriterStore.java, sugoi-api-ldap-utils/src/main/java/fr/insee/sugoi/ldap/utils/mapper/ApplicationLdapMapper.java, sugoi-api-ldap-utils/src/main/java/fr/insee/sugoi/ldap/utils/mapper/GenericLdapMapper.java, sugoi-api-ldap-utils/src/main/java/fr/insee/sugoi/ldap/utils/mapper/GroupLdapMapper.java, sugoi-api-ldap-utils/src/main/java/fr/insee/sugoi/ldap/utils/mapper/LdapMapper.java, sugoi-api-ldap-utils/src/main/java/fr/insee/sugoi/ldap/utils/mapper/OrganizationLdapMapper.java, sugoi-api-ldap-utils/src/main/java/fr/insee/sugoi/ldap/utils/mapper/UserLdapMapper.java, sugoi-api-ldap-utils/src/test/java/fr/insee/sugoi/ldap/utils/mapper/ApplicationLdapMapperFromObjectTest.java, sugoi-api-ldap-utils/src/test/java/fr/insee/sugoi/ldap/utils/mapper/GroupLdapMapperFromObjectTest.java, sugoi-api-ldap-utils/src/test/java/fr/insee/sugoi/ldap/utils/mapper/OrganizationLdapMapperFromObjectTest.java, sugoi-api-ldap-utils/src/test/java/fr/insee/sugoi/ldap/utils/mapper/UserLdapMapperFromObjectTest.java, sugoi-api-test/src/test/resources/scenario/group_scenario_sync.feature
=> [FIX] :bug: remove empty attributes values when adding on ldap

sugoi-api-distribution/sugoi-api-distribution-full-env/src/main/java/fr/insee/sugoi/app/SugoiTestService.java, sugoi-api-file-config-provider/src/main/java/fr/insee/sugoi/config/file/LocalFileRealmProviderDAO.java, sugoi-api-file-store-provider/src/main/java/fr/insee/sugoi/store/file/FileWriterStore.java
=>  [BUG] 🐛 Resources should be closed (#656)

sugoi-api-core/src/main/java/fr/insee/sugoi/core/exceptions/IdNotMatchingException.java, sugoi-api-rest-commons-services/src/main/java/fr/insee/sugoi/commons/services/controller/technics/SugoiAdviceController.java, sugoi-api-rest-services/src/main/java/fr/insee/sugoi/services/controller/ApplicationController.java, sugoi-api-rest-services/src/main/java/fr/insee/sugoi/services/controller/GroupController.java, sugoi-api-rest-services/src/main/java/fr/insee/sugoi/services/controller/OrganizationController.java, sugoi-api-rest-services/src/main/java/fr/insee/sugoi/services/controller/RealmController.java, sugoi-api-rest-services/src/main/java/fr/insee/sugoi/services/controller/UserController.java
=> [BUG] :bug: checking id match on PUT should be case insensitive (#657)

sugoi-api-converter/src/test/java/fr/insee/sugoi/converter/ContactsTest.java, sugoi-api-converter/src/test/java/fr/insee/sugoi/converter/OrganisationTest.java, sugoi-api-file-store-provider/src/test/java/fr/insee/sugoi/store/file/FileWriterStoreTest.java, sugoi-api-file-store-provider/src/test/resources/sugoi-file-tests/apps/Applitest, sugoi-api-file-store-provider/src/test/resources/sugoi-file-tests/orgs/testi, sugoi-api-file-store-provider/src/test/resources/sugoi-file-tests/orgs/testo, sugoi-api-file-store-provider/src/test/resources/sugoi-file-tests/users/testc, sugoi-api-file-store-provider/src/test/resources/sugoi-file-tests/users/testo, sugoi-api-jms-store-provider/src/main/java/fr/insee/sugoi/jms/utils/Converter.java, sugoi-api-ldap-store-provider/src/test/java/fr/insee/sugoi/ldap/LdapWriterStoreTest.java, sugoi-api-ldap-utils/src/test/java/fr/insee/sugoi/ldap/utils/mapper/OrganizationLdapMapperFromObjectTest.java, sugoi-api-ldap-utils/src/test/java/fr/insee/sugoi/ldap/utils/mapper/UserLdapMapperFromObjectTest.java, sugoi-api-model/src/main/java/fr/insee/sugoi/model/Organization.java, sugoi-api-model/src/main/java/fr/insee/sugoi/model/PostalAddress.java, sugoi-api-model/src/main/java/fr/insee/sugoi/model/User.java, sugoi-api-rest-services/src/test/java/fr/insee/sugoi/services/controller/ExportControllerTest.java
Signed-off-by: Chemin Cecile <cecile.chemin@insee.fr>
=> [BC] :boom: Address should appear as an object instead of Array

sugoi-api-core/src/main/java/fr/insee/sugoi/core/configuration/UiMappingService.java, sugoi-api-core/src/test/java/fr/insee/sugoi/core/service/UiMappingServiceTest.java, sugoi-api-ldap-config-provider/src/test/java/fr/insee/sugoi/config/LdapRealmProviderWriteTest.java, sugoi-api-ldap-utils/src/main/java/fr/insee/sugoi/ldap/utils/mapper/RealmLdapMapper.java, sugoi-api-model/src/main/java/fr/insee/sugoi/model/technics/UiField.java, sugoi-api-model/src/main/java/fr/insee/sugoi/model/technics/exceptions/EntryIsNotUIFieldException.java
=> :bug: [BUG] Fix write Organization UiField in Ldap Config (#695)

docs/realm-configuration.md, sugoi-api-core/src/main/java/fr/insee/sugoi/core/service/impl/CredentialsServiceImpl.java, sugoi-api-core/src/test/java/fr/insee/sugoi/core/service/CredentialsServiceTest.java, sugoi-api-event-webhook/src/main/java/fr/insee/sugoi/event/listener/webhook/service/impl/WebHookServiceImpl.java, sugoi-api-event-webhook/src/test/java/fr/insee/sugoi/event/listener/webhook/CredentialWebhookTest.java, sugoi-api-jms-store-provider/src/test/java/fr/insee/sugoi/jms/CredentialsJmsTest.java, sugoi-api-ldap-config-provider/src/main/java/fr/insee/sugoi/config/LdapRealmProviderDAOImpl.java, sugoi-api-ldap-config-provider/src/test/java/fr/insee/sugoi/config/LdapRealmProviderDAOTest.java, sugoi-api-ldap-config-provider/src/test/resources/ldap2.ldif, sugoi-api-ldap-utils/src/main/java/fr/insee/sugoi/ldap/utils/mapper/UserStorageLdapMapper.java, sugoi-api-model/src/main/java/fr/insee/sugoi/model/Realm.java
…torage level
Signed-off-by: Mehdi Maaref <mehdi.maaref@insee.fr>
=> [ENH] :sparkles:  Password configuration can be customized at a userstorage level

sugoi-api-core/src/main/java/fr/insee/sugoi/core/seealso/SeeAlsoService.java, sugoi-api-seealso-http/src/main/java/fr/insee/sugoi/seealso/HttpSeeAlsoDecorator.java, sugoi-api-seealso-ldap/src/main/java/fr/insee/sugoi/seealso/LdapSeeAlsoDecorator.java, sugoi-api-seealso-ldap/src/test/java/fr/insee/sugoi/seealso/LdapSeeAlsoDecoratorTest.java
=> [ENH] :sparkles: LdapSeeAlso can now read any Ldap URL (rfc4516)

sugoi-api-distribution/sugoi-api-distribution-full-env/src/main/resources/ldap-data/init-ldap.ldif, sugoi-api-model/src/main/java/fr/insee/sugoi/model/User.java, sugoi-api-rest-services/src/main/java/fr/insee/sugoi/services/controller/UserController.java, sugoi-api-test/src/main/resources/ldap-data/init-ldap.ldif, sugoi-api-test/src/test/java/fr/insee/sugoi/app/cucumber/glue/UserGlue.java, sugoi-api-test/src/test/resources/scenario/user_scenario_async.feature, sugoi-api-test/src/test/resources/scenario/user_scenario_sync.feature
=> [ENH] ✨ Add filter users by group (#418)

sugoi-api-ldap-store-provider/src/main/java/fr/insee/sugoi/store/ldap/LdapReaderStore.java
=> [BUG] :bug: Get all groups from an application

sugoi-api-core/src/main/java/fr/insee/sugoi/core/event/configuration/EventKeysConfig.java, sugoi-api-core/src/main/java/fr/insee/sugoi/core/service/impl/CredentialsServiceImpl.java, sugoi-api-distribution/sugoi-api-distribution-full-env/src/main/resources/ldap-data/init-ldap.ldif, sugoi-api-event-webhook/src/main/java/fr/insee/sugoi/event/listener/webhook/SugoiEventWebHookProducer.java, sugoi-api-event-webhook/src/test/java/fr/insee/sugoi/event/listener/webhook/SugoiEventWebHookProducerTest.java, sugoi-api-jms-store-provider/src/test/resources/application.properties
=> [BUG] :bug: Fix secondaryEmail is never used

sugoi-api-file-store-provider/src/main/java/fr/insee/sugoi/store/file/FileWriterStore.java, sugoi-api-file-store-provider/src/test/java/fr/insee/sugoi/store/file/FileWriterStoreTest.java, sugoi-api-ldap-store-provider/src/main/java/fr/insee/sugoi/store/ldap/LdapReaderStore.java, sugoi-api-ldap-store-provider/src/test/java/fr/insee/sugoi/ldap/LdapReaderStoreTest.java, sugoi-api-ldap-store-provider/src/test/java/fr/insee/sugoi/ldap/LdapWriterStoreTest.java, sugoi-api-ldap-store-provider/src/test/resources/ldap.ldif, sugoi-api-ldap-utils/src/main/java/fr/insee/sugoi/ldap/utils/LdapFilter.java, sugoi-api-ldap-utils/src/main/java/fr/insee/sugoi/ldap/utils/mapper/GenericLdapMapper.java, sugoi-api-model/src/main/java/fr/insee/sugoi/model/Group.java, sugoi-api-model/src/main/java/fr/insee/sugoi/model/User.java, sugoi-api-rest-services/src/main/java/fr/insee/sugoi/services/controller/ExportController.java, sugoi-api-rest-services/src/main/java/fr/insee/sugoi/services/controller/UserController.java, sugoi-api-rest-services/src/test/java/fr/insee/sugoi/services/controller/ExportControllerTest.java, sugoi-api-seealso-http/src/test/java/fr/insee/sugoi/seealso/HttpSeeAlsoDecoratorTest.java, sugoi-api-test/src/test/resources/scenario/export_scenario.feature, sugoi-api-test/src/test/resources/scenario/user_scenario_sync.feature
=> [BUG] :bug: Fixed filter users by group (#418)

sugoi-api-rest-services/src/main/java/fr/insee/sugoi/services/controller/ExportController.java
Signed-off-by: Mehdi Maaref <mehdimaaref@live.fr>
=> [BUG] :bug: Fix Export csv number of results too low

sugoi-api-ldap-config-provider/src/test/java/fr/insee/sugoi/config/LdapRealmProviderWriteTest.java, sugoi-api-ldap-utils/src/main/java/fr/insee/sugoi/ldap/utils/mapper/RealmLdapMapper.java
issue ref : https://github.com/InseeFr/sugoi-api/issues/749
=> [BUG] :bug: Fix issue : appSource is lost when realm update

sugoi-api-jms-store-provider/src/main/java/fr/insee/sugoi/jms/utils/Converter.java
Signed-off-by: ahliit <cecile.chemin@insee.fr>
=> Fix Habilitation through JMS

sugoi-api-rest-services/src/main/java/fr/insee/sugoi/services/controller/GroupController.java, sugoi-api-test/src/test/resources/scenario/group_scenario2_async.feature, sugoi-api-test/src/test/resources/scenario/group_scenario2_sync.feature
=> [BUG] :bug: Readers can read groups in any app
